AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example next-aws-lambda-webpack-plugin


Resources:

  # ---- DISTRIBUTION ----

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["",[!GetAtt Bucket.Arn, "/*" ]]

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Enabled: true
        Origins:
          - Id: !Ref Bucket
            DomainName: !GetAtt Bucket.DomainName
            S3OriginConfig: {}

        DefaultCacheBehavior:
          TargetOriginId: !Ref Bucket
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: whitelist
              WhitelistedNames: [ NEXT_SSR ]
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref CloudfrontRouterV6

  # ---- ROUTER ----

  CloudfrontRouterV6:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !GetAtt CloudfrontRouter.Arn

  CloudfrontRouter:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt CloudfrontEdgeRole.Arn
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: router/
      Description: >-
        Blueprint for generating a response from viewer-request trigger implemented in NodeJS.
      MemorySize: 128
      Timeout: 1

  # ---- Role ----

  CloudfrontEdgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: log
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*